### ISSUE TITLE
When I compile ft_backend based on cuda10.2 report nvcc fatal  : Unsupported gpu architecture 'compute_80'

### ISSUE THREAD

**Issue by nercoeus** [triton-inference-server/fastertransformer_backend#109]
### Description

```shell
branch: release/v1.2.1_tag
GPU: T4
```

### Reproduced Steps

```shell
git clone https://github.com/triton-inference-server/fastertransformer_backend.git -b release/v1.2.1_tag \
    && cd fastertransformer_backend && mkdir build && cd build \
    && cmake -DTRITON_BUILD_CUDA_VERSION="10.2" -DTRITON_BUILD_CUDA_HOME="/usr/local/cuda/" -DTRITON_BUILD_CUDNN_HOME="/usr/local/cuda/" -DTRITON_ENABLE_GPU=ON -DCMAKE_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_COMMON_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.10 -DTRITON_BACKEND_REPO_TAG=r21.10 .. \
    && make -j 10 install
```

**Comment by byshiue** [comment]
Can you share the full log?

**Comment by nercoeus** [comment]
这是来自QQ邮箱的自动回复邮件。我已收到您的邮件,会尽快与您联系.

**Comment by nercoeus** [comment]
> 

```
cmake -DTRITON_BUILD_CUDA_VERSION="10.2" -DTRITON_BUILD_CUDA_HOME="/usr/local/cuda/" -DTRITON_BUILD_CUDNN_HOME="/usr/local/cuda/" -DTRITON_ENABLE_GPU=OFF -DCMAKE_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_COMMON_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.10 -DTRITON_BACKEND_REPO_TAG=r21.10 ..
make install 
```
err log:
[ 15%] Linking CUDA device code CMakeFiles/tensor.dir/cmake_device_link.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
make[2]: *** [_deps/repo-ft-build/3rdparty/trt_fused_multihead_attention/CMakeFiles/trt_fused_multi_head_attention.dir/build.make:972: _deps/repo-ft-build/3rdparty/trt_fused_multihead_attention/CMakeFiles/trt_fused_multi_head_attention.dir/qkvToContext.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal   : Unsupported gpu architecture 'compute_80'
make[2]: *** [_deps/repo-ft-build/src/fastertransformer/utils/CMakeFiles/tensor.dir/build.make:97: _deps/repo-ft-build/src/fastertransformer/utils/CMakeFiles/tensor.dir/cmake_device_link.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1809: _deps/repo-ft-build/src/fastertransformer/utils/CMakeFiles/tensor.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1652: _deps/repo-ft-build/3rdparty/trt_fused_multihead_attention/CMakeFiles/trt_fused_multi_head_attention.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
