### ISSUE TITLE
Questions about model instances and dynamic batch when setting model concurrency

### ISSUE THREAD

**Issue by YJHMITWEB** [triton-inference-server/fastertransformer_backend#112]
Hi, I'd like to know that for example, when enabling `model concurrency = 2`, does Tritonserver run 2 streams for processing requests? And verses that, if using dynamic batch, is there just 1 stream, and all requests are packed into one batch? And how is model instance related to them?

**Comment by byshiue** [comment]
You can ask this question in tritonserver repo because it is determined by tritonserver, but not backend side.
