### ISSUE TITLE
will FT5.0  be supported ?

### ISSUE THREAD

**Issue by 520jefferson** [triton-inference-server/fastertransformer_backend#15]
@yuanzhedong @PerkzZheng @GwangsooHong @deadeyegoodwin @byshiue 
Is there any plan to support FT5.0,  some model structures like T5 only exist on  FT5.0. 
https://github.com/NVIDIA/FasterTransformer/blob/dev/v5.0_beta/src/fastertransformer/triton_backend/t5/CMakeLists.txt

**Comment by byshiue** [comment]
FT triton backend already supports T5, please refer https://github.com/triton-inference-server/fastertransformer_backend/tree/dev/v1.1_beta#prepare-triton-t5-model-store-in-the-docker.

**Comment by 520jefferson** [comment]
I do as README， but i met some errors as follows:
Firstly, i start the server(the model path cannot be setted like --model-repository=/workspace/build/fastertransformer_backend/all_models/t5/fastertransformer/ , because the program will failed with -- error: creating server: Internal - failed to load all models) as follows:
mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver --model-repository=/workspace/build/fastertransformer_backend/all_models/t5/fastertransformer/1/2-gpu/
![image](https://user-images.githubusercontent.com/5691554/160575003-481ad0fc-05c4-440d-a09a-a7c25494738c.png)

Secondly, i start the client
sh /workspace/fastertransformer_backend/tools/run_client.sh
then i get this in logs:
![image](https://user-images.githubusercontent.com/5691554/160575326-b273b916-204d-430a-8341-18fe510fcae5.png)
