### ISSUE TITLE
does it also support general transformer encoders like bert?

### ISSUE THREAD

**Issue by zhanghaoie** [triton-inference-server/fastertransformer_backend#18]

**Comment by byshiue** [comment]
This backend still not support encoder model.

**Comment by byshiue** [comment]
BERT is supported in latest release. Please refer https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/bert_guide.md.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
