### ISSUE TITLE
Dynamic Batching with Different Sized Context (Ragged)

### ISSUE THREAD

**Issue by jimwu6** [triton-inference-server/fastertransformer_backend#23]
I see that it is currently not supported (https://github.com/triton-inference-server/fastertransformer_backend/blob/main/src/libfastertransformer.cc#L1044), but I want to be be able to batch input_ids with different context length, e.g. batch [1, 1, 25] with [1, 1, 10].

**Comment by byshiue** [comment]
Batching is a feature of triton server, FT does not have way to control it in backend. 
You can pad your input to same maximum input length when you send the request to server.

**Comment by jimwu6** [comment]
Ideally we'd like to keep `max_seq_len` and `max_input_len` to be equal and not pad requests made to the server (unless they are explicitly batched). From what I can tell, the handling of ragged batching is accounted for by the backend (https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md); I'm trying to implement this feature by finding the max sequence length of the batch before [this loop](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/src/libfastertransformer.cc#L1056) and then padding the tensors before this function terminates, but it seems non-trivial because of the way the memory is allocated. Any pointers?

**Comment by byshiue** [comment]
You can ask this problem in the repo of triton backend, I don't have idea for this issue, too.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
