### ISSUE TITLE
Does FT supports serving multiple models concurrently?

### ISSUE THREAD

**Issue by PKUFlyingPig** [triton-inference-server/fastertransformer_backend#35]
If there are multiple models in the model-repository, how will FT launch model instances? Say there are 4 GPUs in total, I launch the Bert and GPT model each with 1 instance, will they both be placed on the first GPU? Can I control the instance placement policy?

**Comment by byshiue** [comment]
You can choose which GPU by setting `CUDA_VISIBLE_DEVICES` during launching server.
