### ISSUE TITLE
Support mt5 (t5 v1.1)?

### ISSUE THREAD

**Issue by hong8c** [triton-inference-server/fastertransformer_backend#37]
Is there any plan to support mt5 (t5 v1.1)?
Thank you.

**Comment by byshiue** [comment]
It is supported. The workflow is same to T5.

**Comment by hong8c** [comment]
Thank you, @byshiue However when I download T5 v1.1 models from huggingface and followed the same workflow, I've got some wield outputs. I tested several times. I will post more detailed information about the problem. Thank you!

**Comment by byshiue** [comment]
This is supported since v1.2. Here are some guide https://github.com/NVIDIA/FasterTransformer/blob/main/docs/t5_guide.md#how-to-use. You can reuse the t5 example to run mt5 easily.
