### ISSUE TITLE
Recommendation for the complete BERT model deployment on Triton + fastertransformer backend

### ISSUE THREAD

**Issue by vblagoje** [triton-inference-server/fastertransformer_backend#46]
### Description

What is the recommended approach for practical complete BERT model deployment on Triton with the faster transformer backend? 

So far, I have successfully converted  the HF bert-base-uncased model weights using `huggingface_bert_convert.py`, deployed it to the triton server with fastertransformer backend and completed the BERT `identity_test.py`. I noticed that the converted model is, in fact, a BERT encoder without model embeddings and a pooler + classification head on top. After watching the Faster Transformer presentation at https://developer.nvidia.com/gtc/2020/video/s21417, I understand why the optimization focused on the BERT encoder. Still, I am baffled on how to use a complete BERT model on Triton with fastertransformer backend practically? Resolving embeddings and invocation of pooling and qa/classification head on top match nicely with the pre/post-processing paradigms. Is that the recommended approach to complete the full inference on, for example, BERT QA model? If so, do pre/post-processing components have access to GPUs? Any other recommendations or guidelines? 
TIA

**Comment by vblagoje** [comment]
@byshiue it would be great if you could enable discussions for this Github repo. Following this [guideline](https://docs.github.com/en/discussions/quickstart) you can do it in no time. Thanks for all your amazing work.

**Comment by byshiue** [comment]
> Still, I am baffled on how to use a complete BERT model on Triton with fastertransformer backend practically?

The simplest and fast way to test is adding pre/post processing in the `identity_test.py` by pytorch directly. Namely, you run pre-processing to get embedding, converting them to numpy and send to FT backend, receiving results from FT backend and pass into post-processing of pytorch.

When you verify the correctness, you can use pytorch backend to run the pre/post processing next. And link the pre/post processing and FT backend by ensemble feature of triton backend. You can make sure the buffer are on GPU all the time by the ensemble feature triton backend.

**Comment by vblagoje** [comment]
Thanks for the guidance @byshiue , closing this issue.

**Comment by sfc-gh-zhwang** [comment]
@byshiue what is the difference between doing pre/post process directly vs using the ensemble feature in terms of performance?
