### ISSUE TITLE
GPTJ end_id usage and behavior

### ISSUE THREAD

**Issue by timofeev1995** [triton-inference-server/fastertransformer_backend#54]
Hello. At first want to thank you a lot for your job and this framework. Really appreciated!
I have a question about generation process with GPT-j.
Everything is set up, generation works well, but end_id
```
{
    name: "end_id"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  }
```
seems like it doesnt work as expected for generation.

Lets say I have a prefix for generation:
```
Jack: Hello buddy
Mike: Hello there!
Jack:
```
and want my generation process to stop when it reachs end_id = 198 (which is token for \n) => so I want only generate one turn of this "dialogue".

My expected output is 
```
Jack: Hello buddy\nMike: Hello there!\nJack: How are you?
```
but I get
```
Jack: Hello buddy\nMike: Hello there!\nJack: How are you?\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
```
and generation continues until max_steps reached

Can you please point at part of code or possible mistake made by me to check that kind of behavior?
Thank you!

**Comment by byshiue** [comment]
What's the sequence length? When you set end_id, the program will initialize the buffer by end_id first, and then start generation. 
So, all tokens after real output would be 198 in your case.

**Comment by timofeev1995** [comment]
Really appreciated for your reply. Thanks!
Sequence length is exactly the same I passed to the generation.
