### ISSUE TITLE
Is there any kind of caching?

### ISSUE THREAD

**Issue by timofeev1995** [triton-inference-server/fastertransformer_backend#55]
Hello.

### Description
Difference in performance in cases of similar requests vs different requests.
I use custom client and do performance testing of GPTJ-6B model.
In case when i use only one string (just mocked while prototyping) as prefix for generation (same for all requests), I get really good performance:

(below is output of https://github.com/wg/wrk tool for performance testing)
10 threads, prefix length is 512, 50 tokens to be generated.
```
Latency Distribution
     50%    2.24s 
     75%    2.25s 
     90%    2.25s 
     99%    2.27s 
```

But if I use different strings as a prefix, it looks like queue of requests if growing fast, and I get like:
```
Latency Distribution
     50%    3.17s 
     75%    3.28s 
     90%    4.12s 
     99%    5.89s 
```

### Environment
I use custom docker container, based on nvcr.io/nvidia/tritonserver:22.03-py3 with fastertransformer_backend built.
Also I use ensemble setup from here: https://github.com/triton-inference-server/fastertransformer_backend/tree/main/all_models/gptj
The model checkpoint converted and set as it described here: https://developer.nvidia.com/blog/deploying-gpt-j-and-t5-with-fastertransformer-and-triton-inference-server/

### Thoughts
I noticed, that when I use only one string, there is more consistent batches I can see in triton-server logs:
```
I1013 20:56:40.491431 567 libfastertransformer.cc:886] get total batch_size = 10
I1013 20:56:40.491448 567 libfastertransformer.cc:1296] get input count = 16
```

But when I use different feed, I see a lot of partial batches of my 10-threads client feed, like:
```
I1013 20:56:40.491431 567 libfastertransformer.cc:886] get total batch_size = 3
I1013 20:56:40.491448 567 libfastertransformer.cc:1296] get input count = 16
```
+ 
```
I1013 20:56:40.491431 567 libfastertransformer.cc:886] get total batch_size = 4
I1013 20:56:40.491448 567 libfastertransformer.cc:1296] get input count = 16
```
+ 
```
I1013 20:56:40.491431 567 libfastertransformer.cc:886] get total batch_size = 1
I1013 20:56:40.491448 567 libfastertransformer.cc:1296] get input count = 16
```
etc.

Is there any kind of cache in fastertransformer framework, that can give that kind of behaviour?
Or, maybe, low performance on different inputs can be caused by something else?
Thank you in advance!

**Comment by byshiue** [comment]
There are two phase in GPTJ. 

The first phase is called context phase, which generates k/v caches of inputs. In such phase, same requests generate same caches. So, we do an optimization here to prevent the overhead of same request. 

The second phase is called generation phase. In this phase, even if the requests are same, they may generate different results under different random seed. So, there is no optimization here. 

So, it is not a cache mechanism in FasterTransformer for same request, but a computing optimization for same inputs/outputs.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
