### ISSUE TITLE
Support BLOOM model?

### ISSUE THREAD

**Issue by pai4451** [triton-inference-server/fastertransformer_backend#69]
Hi triton developer,

Currently, the fastertransformer backend only supports GPT, GPT-J, T5, GPT-NeoX and Bert. 

I am wondering is there any plan to support [bigscience/bloom](https://huggingface.co/bigscience/bloom) model? If not, is it possible (and how) to convert BLOOM to one of the supported models and serve by triton with fastertransformer backend?

**Comment by byshiue** [comment]
We have plan to support bloom. You cannot use gpt backend to run bloom now because their model architectures are little different.

**Comment by pai4451** [comment]
> We have plan to support bloom. You cannot use gpt backend to run bloom now because their model architectures are little different.

Thanks @byshiue, I’m glad that BLOOM will be supporting. Will this comes in a near future?

**Comment by byshiue** [comment]
This is supported in latest v1.3 release. Thank you for the suggestion.

**Comment by pai4451** [comment]
@byshiue Thanks for supporting BLOOM. I checked the [ft backend docs on BLOOM](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md) there should be a test code `tools/gpt/bloom_test.py` for BLOOM but somehow I couldn't find it in the repo. Also, can you share the parameter settings `config.ini` for BLOOM-176b as well?
